### ISSUE TITLE
Dejar el juego listo para "publicar"

### ISSUE THREAD

**Issue by PabloAlejos** [PabloAlejos/Machine-Learning-GameDev#32]
Se harán las siguientes tareas:
- [x] Añadir contador de vida a los enemigos #31 
- [x] Dejar los estados perfectamente preparados #29 
- [x] Permitir movimiento vertical al jugador #30 
- [x] Ocultar las opciones de entrenamiento al jugador ( dejar en pantalla únicamente el juego)
- [x] Crear una transición entre el menú principal y la pantalla de juego #35
- [x] Introducir la aparición de powerUps #34
- [ ] Modificar los sprites de impacto y explosión #36
- [x] Añadir efectos de sonido #26 
- [x] Añadir animación explosión jugador #38
